# Generated by Django 3.0.7 on 2020-09-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('declined', 'declined'), ('pending', 'pending'), ('viewed', 'viewed'), ('inprocess', 'inprocess'), ('notviewed', 'notviewed')], default='notviewed', max_length=20),
        ),
    ]
